# Render.com deployment configuration
services:
  - type: web
    name: portfolio
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/cv-status
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: EMAIL_USER
        sync: false  # Set manually in Render dashboard
      - key: EMAIL_PASSWORD  
        sync: false  # Set manually in Render dashboard

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio_user
    plan: starter